﻿services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev
    platform: linux/amd64   # needed if you're on Apple Silicon
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"